on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Checkout Sample Repository
        uses: actions/checkout@v2
        with:
          repository: deploca/sample-microservice-school
          path: /tmp/src
      - name: Publish sample repository
        run: |
          chmod +x /tmp/src/publish.sh
          /tmp/src/publish.sh
      - name: Upload action
        uses: ./ # Uses an action in the root directory
        id: uploader
        with:
          path: /tmp/publish/
          target: my-sample-app:development
      # Use the output from the `hello` step
      - name: Get the output result
        run: echo "The result is ${{ steps.uploader.outputs.result }}"
